/*
 * TrainingBandpassFilter.h
 *
 * 5th Order Butterworth Bandpass Filter (0.5-30 Hz at 250Hz)
 * Matches the training script preprocessing pipeline exactly
 *
 * Filter Specifications:
 *   - Type: Butterworth bandpass
 *   - Order: 5
 *   - Cutoff frequencies: 0.5 Hz (low), 30 Hz (high)
 *   - Sample rate: 250 Hz
 *   - Implementation: 5 cascaded second-order sections (biquads)
 *
 * Stability: All poles inside unit circle (max magnitude: 0.996220)
 *
 * Generated by: generate_training_filter_coefficients.py
 */

#ifndef TRAINING_BANDPASS_FILTER_H
#define TRAINING_BANDPASS_FILTER_H

#include <Arduino.h>

class TrainingBandpassFilter {
public:
    TrainingBandpassFilter();

    // Process single sample through the filter
    float process(float input);

    // Reset filter state (call before processing new data stream)
    void reset();

private:
    // Number of second-order sections
    static const int NUM_SECTIONS = 5;

    // SOS coefficients [b0, b1, b2, a1, a2] for each section
    // Note: a0 = 1.0 is implicit and not stored
    static const float b0[NUM_SECTIONS];
    static const float b1[NUM_SECTIONS];
    static const float b2[NUM_SECTIONS];
    static const float a1[NUM_SECTIONS];
    static const float a2[NUM_SECTIONS];

    // Filter state variables (Direct Form II)
    float w1[NUM_SECTIONS];  // Previous state 1
    float w2[NUM_SECTIONS];  // Previous state 2
};

#endif // TRAINING_BANDPASS_FILTER_H
